# Generated by Django 2.1.3 on 2019-02-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
