# Generated by Django 2.1.3 on 2019-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190128_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
