# Generated by Django 2.1.3 on 2019-01-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_main',
        ),
    ]
